-- approval_log
create table if not exists public.approval_log (
  id bigint generated by default as identity primary key,
  approval_queue_id bigint references public.approval_queue(id) on delete cascade,
  action text not null,              -- 'created' | 'approved' | 'rejected'
  actor_slack_id text,
  actor_name text,
  notes text,
  created_at timestamptz default now()
);