-- approval_queue
create table if not exists public.approval_queue (
  id bigint generated by default as identity primary key,
  gmail_message_id text not null,
  student_email text not null,
  student_name text default '',
  subject text not null,
  original_content text not null,
  ai_response text not null,
  category text,
  urgency int,
  status text not null default 'processed',
  slack_channel text,
  slack_message_ts text,
  reviewed_at timestamptz,
  reviewer_slack_id text,
  reviewer_name text
);
